# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  job:
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build!

- stage: QA
  job:
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
    - script: echo QA!

